site_name: GHOST IN THE CLOUD
site_url: http://127.0.0.1:8000/
site_author: 'ndu69110'
copyright: Copyright &copy; 2025 | Built using MkDocs, Material for MkDocs and PyMdown Extensions <br> Hosted with â¤ï¸ in Github Pages 
docs_dir: docs/

theme:
  font:
    text: Roboto
  name: material
  language: fr
  color_mode: dark
  custom_dir: custom_theme
  logo: logo/logo.webp
  favicon: logo/icon.webp
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
    ##  toggle:
    ##    icon: material/weather-sunny        # ğŸ‘ˆ default: material/brightness-7 
    ##    name: Switch to light mode
    # Palette toggle for light mode
    ##- scheme: default
    ##  toggle:
    ##    icon: material/weather-night        # ğŸ‘ˆ default: material/brightness-4
    ##    name: Switch to dark mode  
  features:
    - header.hide_repo_revision               # ğŸ‘ˆ empÃªche lâ€™affichage du numÃ©ro ou texte sous le nom
    #- header.autohide                        # ğŸ‘ˆ if commented: the header remains visible 
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate                           # ğŸ‘ˆ show to to the left instead to the right
    - content.action.view                     # ğŸ‘ˆ adds "View source of this page"
    #- navigation.footer    
    - toc.sections
    - search.suggest
    - search.highlight
    - search.share
    - search.related
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tooltips
    - content.footnote.tooltips
    - content.tabs.link

plugins:
  - open-in-new-tab
  - blog:
      archive: false      
      archive_date_format: MMMM yyyy
      enabled: true                           # ğŸ‘ˆ if false: hide the blog
      blog_toc: true                          # ğŸ‘ˆ if false: hide the blog TOC
      post_date_format: full
      post_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      post_url_format: "{categories}/{slug}"
      post_url_max_categories: 2
      post_readtime: true                     # ğŸ‘ˆ if false: hide the read time
      categories: true                        # ğŸ‘ˆ if false: hide the categories
      categories_name: Categories
      authors_file: .authors.yml
      authors: true                           # ğŸ‘ˆ if false: hide the authors
      draft: true
      draft_if_future_date: true
      pagination_per_page: 5
  - search:
      enabled: true                           # ğŸ‘ˆ if false: hide the search bar
      lang: fr
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer     
  - tags:
      tags_slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      tags_slugify_separator: _
      tags_slugify_format: "tag:{slug}"
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      tags_sort_reverse: true
      tags_name_property: tags
      tags_name_variable: tags
      #listings: false                        # ğŸ‘ˆ if false: hide the tags
      listings_sort_by: !!python/name:material.plugins.tags.item_title
      listings_sort_reverse: false            # ğŸ‘ˆ if false: show the tags in the correct order
      tags_sort_by: !!python/name:material.plugins.tags.tag_name_casefold
      tags_sort_reverse: true
      #listings_directive: $tags              # ğŸ‘ˆ hide tags if not commmented

extra_css:
- assets/css/extra.css
- overrides/extra.css
- assets/stylesheets/extra.css

extra_javascript:
- assets/js/timeago.min.js
- assets/js/timeago_mkdocs_material.js

extra:
  social:
    - icon: 'simple/github'
      link: 'https://github.com/ndu69110'
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nicolas-dupre-94b2a078/
      name: nicolas dupre on Linkedin
  generator: false                            # ğŸ‘ˆ if true : show auto footer "made with ..."

repo_url: https://github.com/ndu69110
repo_name: ndu69110
repo_icon: fontawesome/brands/github
edit_uri: /ndu69110/MKDocs/blob/main/docs     # ğŸ‘ˆ If you set it to "" (empty string), the edit links are disabled.

markdown_extensions:
  - markdown.extensions.meta:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
      PLACE_MARKER: "<!-- Footnotes -->"
  - markdown.extensions.toc:
      permalink: true
  - markdown.extensions.md_in_html:
  - pymdownx.betterem:                        # ğŸ‘ˆ add
  - pymdownx.blocks.caption:
  - pymdownx.caret:
  - pymdownx.mark:
  - pymdownx.keys:
  - pymdownx.tilde:
  - pymdownx.critic:
      mode: view
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite:
  - pymdownx.snippets:
      base_path: 'theme/snippets'
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      pygments_lang_class: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
  - pymdownx.smartsymbols:
  - pymdownx.magiclink:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.blocks.details:
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition:
      types:
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
        - download
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
      title: SOMMAIRE                         # ğŸ‘ˆ TOC name
      permalink_title: Anchor link to this section for reference
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  
nav:
  - Accueil: index.md
  - Gestion du site: _GESTION-SITE/gestion-site.md
  - Blog:
      - blog/index.md
      - blog/author/team.md
  - Wiki:
      - wiki/index.md
      - wiki/installation.md
      - wiki/guide-utilisateur.md
      - wiki/guide-developpement.md
  - Git et Github:
      - Concept: GIT-GITHUB/git_concept.md
      - Objectif de Git: GIT-GITHUB/git_objectif.md
      - Trier: GIT-GITHUB/git_test.md
      - Host: GIT-GITHUB/git_host-github-pages.md
  - test: test.md
  - Guide utilisateur:
      - RÃ©diger votre doc: test.md
      - Personnaliser le style: test.md
  - Liens utiles: ess.md
  - Tags: _TAGS/tags.md
  - Contact: _CONTACT/contact.md
